#!/bin/sh
#. /etc/os-release
PRETTY_NAME=`awk -F= '$1=="PRETTY_NAME" { print $2 ;}' /etc/os-release | tr -d '"'`
VERSION_ID=`awk -F= '$1=="VERSION_ID" { print $2 ;}' /etc/os-release`
UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)
cat > /etc/motd << EOF
[38;5;14m%++++++++++++++++++++ SERVER INFO ++++++++++++++++++++%
%                                                     %
   [38;5;14mA    [38;5;12m  Name[38;5;14m: `hostname`
  /I\   [38;5;12mUptime[38;5;14m: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINUTES minutes
 //I\\\  [38;5;12mMemory[38;5;14m: `free -m | head -n 2 | tail -n 1 | awk {'print  $2'}`M
///I\\\\\ [38;5;12m  Swap[38;5;14m: `free -m | tail -n 1 | awk {'print $2'}`M 
'//I\\\' [38;5;12m  Disk[38;5;14m: `df -h / | awk  '{ a = $2 } END { print a }'`
  'I' [38;5;12m     CPU[38;5;14m:`cat /proc/cpuinfo | grep 'model name' | head  -1 | cut -d':' -f2`
   I
   I    [38;5;12m Kernel[38;5;14m: `uname -r`
   I    [38;5;12m Distro[38;5;14m: $PRETTY_NAME
   I    [38;5;12mVersion[38;5;14m: $VERSION_ID
   I
   I    [38;5;12m   CPU Load[38;5;14m: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}'`
   I    [38;5;12mFree Memory[38;5;14m: `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M
   I    [38;5;12mFree   Swap[38;5;14m: `free -m | tail -n 1 | awk {'print $4'}`M
   I    [38;5;12mFree   Disk[38;5;14m: `df -h / | awk '{ a =  $2 } END { print a }'`
   I
   +    [38;5;12meth0 Address[38;5;14m: `ifconfig eth0 | grep "inet addr" |  awk -F: '{print $2}' | awk '{print $1}'`
[38;5;14m%                                                     %
%++++++++++++++++++++ SERVER INFO ++++++++++++++++++++%
EOF
