#!/usr/bin/fish

for sv in @ @root @music @encrypted
  set date (string split '-' (date -I))
  set snapshot_dir /.snapshots/$sv/$date[1]/$date[2]/$date[3]

  if not test -d $snapshot_dir
    set current_month_dir /.snapshots/$sv/$date[1]/$date[2]
    mkdir -p $current_month_dir

    btrfs subvolume snapshot /.subvolumes/$sv $snapshot_dir

    for year in /.snapshots/$sv/*
      for month in $year/*
        if test $month = $current_month_dir && test (ls $month | count) -gt 7
          btrfs subvolume delete (ls $month | head -1)
        else if test (ls $month | head -n-1 | count) -ne 0
          btrfs subvolume delete (ls $month | head -n-1)
        end
      end
    end
  end
end
